import { z } from "zod";
/**
 * Country and time-zone picklists. GENERATED — do not edit by hand.
 *
 * Regenerate with `node scripts/generate-geo.mjs` (see that file for why this
 * is baked rather than computed in the browser).
 *
 * 263 countries, 320 zones.
 */

export interface CountryOption {
  /** ISO 3166-1 alpha-2. This is what gets stored. */
  readonly code: string;
  readonly name: string;
}

export interface TimeZoneMeta {
  /** Daylight-independent display name, e.g. "India Standard Time". */
  readonly name: string;
  /** Colloquial abbreviation, e.g. "IST" / "ET". Null when the zone has none. */
  readonly abbr: string | null;
}

/** Launch markets, pinned to the head of COUNTRIES. */
export const PINNED_COUNTRY_CODES: readonly string[] = ["US", "IN", "GB"];

/** US, IN, GB first, then alphabetical. */
export const COUNTRIES: readonly CountryOption[] = [
  { code: "US", name: "United States" },
  { code: "IN", name: "India" },
  { code: "GB", name: "United Kingdom" },
  { code: "AF", name: "Afghanistan" },
  { code: "AX", name: "Åland Islands" },
  { code: "AL", name: "Albania" },
  { code: "DZ", name: "Algeria" },
  { code: "AS", name: "American Samoa" },
  { code: "AD", name: "Andorra" },
  { code: "AO", name: "Angola" },
  { code: "AI", name: "Anguilla" },
  { code: "AQ", name: "Antarctica" },
  { code: "AG", name: "Antigua & Barbuda" },
  { code: "AR", name: "Argentina" },
  { code: "AM", name: "Armenia" },
  { code: "AW", name: "Aruba" },
  { code: "AU", name: "Australia" },
  { code: "AT", name: "Austria" },
  { code: "AZ", name: "Azerbaijan" },
  { code: "BS", name: "Bahamas" },
  { code: "BH", name: "Bahrain" },
  { code: "BD", name: "Bangladesh" },
  { code: "BB", name: "Barbados" },
  { code: "BY", name: "Belarus" },
  { code: "BE", name: "Belgium" },
  { code: "BZ", name: "Belize" },
  { code: "BJ", name: "Benin" },
  { code: "DY", name: "Benin" },
  { code: "BM", name: "Bermuda" },
  { code: "BT", name: "Bhutan" },
  { code: "BO", name: "Bolivia" },
  { code: "BA", name: "Bosnia & Herzegovina" },
  { code: "BW", name: "Botswana" },
  { code: "BR", name: "Brazil" },
  { code: "IO", name: "British Indian Ocean Territory" },
  { code: "VG", name: "British Virgin Islands" },
  { code: "BN", name: "Brunei" },
  { code: "BG", name: "Bulgaria" },
  { code: "BF", name: "Burkina Faso" },
  { code: "HV", name: "Burkina Faso" },
  { code: "BI", name: "Burundi" },
  { code: "KH", name: "Cambodia" },
  { code: "CM", name: "Cameroon" },
  { code: "CA", name: "Canada" },
  { code: "CV", name: "Cape Verde" },
  { code: "BQ", name: "Caribbean Netherlands" },
  { code: "KY", name: "Cayman Islands" },
  { code: "CF", name: "Central African Republic" },
  { code: "TD", name: "Chad" },
  { code: "CL", name: "Chile" },
  { code: "CN", name: "China" },
  { code: "CX", name: "Christmas Island" },
  { code: "CC", name: "Cocos (Keeling) Islands" },
  { code: "CO", name: "Colombia" },
  { code: "KM", name: "Comoros" },
  { code: "CG", name: "Congo - Brazzaville" },
  { code: "CD", name: "Congo - Kinshasa" },
  { code: "ZR", name: "Congo - Kinshasa" },
  { code: "CK", name: "Cook Islands" },
  { code: "CR", name: "Costa Rica" },
  { code: "CI", name: "Côte d’Ivoire" },
  { code: "HR", name: "Croatia" },
  { code: "CU", name: "Cuba" },
  { code: "AN", name: "Curaçao" },
  { code: "CW", name: "Curaçao" },
  { code: "CY", name: "Cyprus" },
  { code: "CZ", name: "Czechia" },
  { code: "DK", name: "Denmark" },
  { code: "DJ", name: "Djibouti" },
  { code: "DM", name: "Dominica" },
  { code: "DO", name: "Dominican Republic" },
  { code: "EC", name: "Ecuador" },
  { code: "EG", name: "Egypt" },
  { code: "SV", name: "El Salvador" },
  { code: "GQ", name: "Equatorial Guinea" },
  { code: "ER", name: "Eritrea" },
  { code: "EE", name: "Estonia" },
  { code: "SZ", name: "Eswatini" },
  { code: "ET", name: "Ethiopia" },
  { code: "FK", name: "Falkland Islands" },
  { code: "FO", name: "Faroe Islands" },
  { code: "FJ", name: "Fiji" },
  { code: "FI", name: "Finland" },
  { code: "FR", name: "France" },
  { code: "FX", name: "France" },
  { code: "GF", name: "French Guiana" },
  { code: "PF", name: "French Polynesia" },
  { code: "TF", name: "French Southern Territories" },
  { code: "GA", name: "Gabon" },
  { code: "GM", name: "Gambia" },
  { code: "GE", name: "Georgia" },
  { code: "DD", name: "Germany" },
  { code: "DE", name: "Germany" },
  { code: "GH", name: "Ghana" },
  { code: "GI", name: "Gibraltar" },
  { code: "GR", name: "Greece" },
  { code: "GL", name: "Greenland" },
  { code: "GD", name: "Grenada" },
  { code: "GP", name: "Guadeloupe" },
  { code: "GU", name: "Guam" },
  { code: "GT", name: "Guatemala" },
  { code: "GG", name: "Guernsey" },
  { code: "GN", name: "Guinea" },
  { code: "GW", name: "Guinea-Bissau" },
  { code: "GY", name: "Guyana" },
  { code: "HT", name: "Haiti" },
  { code: "HN", name: "Honduras" },
  { code: "HK", name: "Hong Kong SAR China" },
  { code: "HU", name: "Hungary" },
  { code: "IS", name: "Iceland" },
  { code: "ID", name: "Indonesia" },
  { code: "IR", name: "Iran" },
  { code: "IQ", name: "Iraq" },
  { code: "IE", name: "Ireland" },
  { code: "IM", name: "Isle of Man" },
  { code: "IL", name: "Israel" },
  { code: "IT", name: "Italy" },
  { code: "JM", name: "Jamaica" },
  { code: "JP", name: "Japan" },
  { code: "JE", name: "Jersey" },
  { code: "JO", name: "Jordan" },
  { code: "KZ", name: "Kazakhstan" },
  { code: "KE", name: "Kenya" },
  { code: "KI", name: "Kiribati" },
  { code: "KW", name: "Kuwait" },
  { code: "KG", name: "Kyrgyzstan" },
  { code: "LA", name: "Laos" },
  { code: "LV", name: "Latvia" },
  { code: "LB", name: "Lebanon" },
  { code: "LS", name: "Lesotho" },
  { code: "LR", name: "Liberia" },
  { code: "LY", name: "Libya" },
  { code: "LI", name: "Liechtenstein" },
  { code: "LT", name: "Lithuania" },
  { code: "LU", name: "Luxembourg" },
  { code: "MO", name: "Macao SAR China" },
  { code: "MG", name: "Madagascar" },
  { code: "MW", name: "Malawi" },
  { code: "MY", name: "Malaysia" },
  { code: "MV", name: "Maldives" },
  { code: "ML", name: "Mali" },
  { code: "MT", name: "Malta" },
  { code: "MH", name: "Marshall Islands" },
  { code: "MQ", name: "Martinique" },
  { code: "MR", name: "Mauritania" },
  { code: "MU", name: "Mauritius" },
  { code: "YT", name: "Mayotte" },
  { code: "MX", name: "Mexico" },
  { code: "FM", name: "Micronesia" },
  { code: "MD", name: "Moldova" },
  { code: "MC", name: "Monaco" },
  { code: "MN", name: "Mongolia" },
  { code: "ME", name: "Montenegro" },
  { code: "MS", name: "Montserrat" },
  { code: "MA", name: "Morocco" },
  { code: "MZ", name: "Mozambique" },
  { code: "BU", name: "Myanmar (Burma)" },
  { code: "MM", name: "Myanmar (Burma)" },
  { code: "NA", name: "Namibia" },
  { code: "NR", name: "Nauru" },
  { code: "NP", name: "Nepal" },
  { code: "NL", name: "Netherlands" },
  { code: "NC", name: "New Caledonia" },
  { code: "NZ", name: "New Zealand" },
  { code: "NI", name: "Nicaragua" },
  { code: "NE", name: "Niger" },
  { code: "NG", name: "Nigeria" },
  { code: "NU", name: "Niue" },
  { code: "NF", name: "Norfolk Island" },
  { code: "KP", name: "North Korea" },
  { code: "MK", name: "North Macedonia" },
  { code: "MP", name: "Northern Mariana Islands" },
  { code: "NO", name: "Norway" },
  { code: "OM", name: "Oman" },
  { code: "PK", name: "Pakistan" },
  { code: "PW", name: "Palau" },
  { code: "PS", name: "Palestinian Territories" },
  { code: "PA", name: "Panama" },
  { code: "PG", name: "Papua New Guinea" },
  { code: "PY", name: "Paraguay" },
  { code: "PE", name: "Peru" },
  { code: "PH", name: "Philippines" },
  { code: "PN", name: "Pitcairn Islands" },
  { code: "PL", name: "Poland" },
  { code: "PT", name: "Portugal" },
  { code: "PR", name: "Puerto Rico" },
  { code: "QA", name: "Qatar" },
  { code: "RE", name: "Réunion" },
  { code: "RO", name: "Romania" },
  { code: "RU", name: "Russia" },
  { code: "SU", name: "Russia" },
  { code: "RW", name: "Rwanda" },
  { code: "WS", name: "Samoa" },
  { code: "SM", name: "San Marino" },
  { code: "ST", name: "São Tomé & Príncipe" },
  { code: "SA", name: "Saudi Arabia" },
  { code: "SN", name: "Senegal" },
  { code: "CS", name: "Serbia" },
  { code: "RS", name: "Serbia" },
  { code: "YU", name: "Serbia" },
  { code: "SC", name: "Seychelles" },
  { code: "SL", name: "Sierra Leone" },
  { code: "SG", name: "Singapore" },
  { code: "SX", name: "Sint Maarten" },
  { code: "SK", name: "Slovakia" },
  { code: "SI", name: "Slovenia" },
  { code: "SB", name: "Solomon Islands" },
  { code: "SO", name: "Somalia" },
  { code: "ZA", name: "South Africa" },
  { code: "GS", name: "South Georgia & South Sandwich Islands" },
  { code: "KR", name: "South Korea" },
  { code: "SS", name: "South Sudan" },
  { code: "ES", name: "Spain" },
  { code: "LK", name: "Sri Lanka" },
  { code: "BL", name: "St. Barthélemy" },
  { code: "SH", name: "St. Helena" },
  { code: "KN", name: "St. Kitts & Nevis" },
  { code: "LC", name: "St. Lucia" },
  { code: "MF", name: "St. Martin" },
  { code: "PM", name: "St. Pierre & Miquelon" },
  { code: "VC", name: "St. Vincent & Grenadines" },
  { code: "SD", name: "Sudan" },
  { code: "SR", name: "Suriname" },
  { code: "SJ", name: "Svalbard & Jan Mayen" },
  { code: "SE", name: "Sweden" },
  { code: "CH", name: "Switzerland" },
  { code: "SY", name: "Syria" },
  { code: "TW", name: "Taiwan" },
  { code: "TJ", name: "Tajikistan" },
  { code: "TZ", name: "Tanzania" },
  { code: "TH", name: "Thailand" },
  { code: "TL", name: "Timor-Leste" },
  { code: "TP", name: "Timor-Leste" },
  { code: "TG", name: "Togo" },
  { code: "TK", name: "Tokelau" },
  { code: "TO", name: "Tonga" },
  { code: "TT", name: "Trinidad & Tobago" },
  { code: "TN", name: "Tunisia" },
  { code: "TR", name: "Türkiye" },
  { code: "TM", name: "Turkmenistan" },
  { code: "TC", name: "Turks & Caicos Islands" },
  { code: "TV", name: "Tuvalu" },
  { code: "UM", name: "U.S. Outlying Islands" },
  { code: "VI", name: "U.S. Virgin Islands" },
  { code: "UG", name: "Uganda" },
  { code: "UA", name: "Ukraine" },
  { code: "AE", name: "United Arab Emirates" },
  { code: "UK", name: "United Kingdom" },
  { code: "UY", name: "Uruguay" },
  { code: "UZ", name: "Uzbekistan" },
  { code: "NH", name: "Vanuatu" },
  { code: "VU", name: "Vanuatu" },
  { code: "VA", name: "Vatican City" },
  { code: "VE", name: "Venezuela" },
  { code: "VD", name: "Vietnam" },
  { code: "VN", name: "Vietnam" },
  { code: "WF", name: "Wallis & Futuna" },
  { code: "EH", name: "Western Sahara" },
  { code: "YD", name: "Yemen" },
  { code: "YE", name: "Yemen" },
  { code: "ZM", name: "Zambia" },
  { code: "RH", name: "Zimbabwe" },
  { code: "ZW", name: "Zimbabwe" },
];

export const TIME_ZONES_BY_COUNTRY: Readonly<Record<string, readonly string[]>> = {
  US: [
    "America/Adak",
    "America/Anchorage",
    "America/Chicago",
    "America/Denver",
    "America/Los_Angeles",
    "America/New_York",
    "America/Phoenix",
    "Pacific/Honolulu",
  ],
  IN: ["Asia/Kolkata"],
  GB: ["Europe/London"],
  AF: ["Asia/Kabul"],
  AX: ["Europe/Mariehamn"],
  AL: ["Europe/Tirane"],
  DZ: ["Africa/Algiers"],
  AS: ["Pacific/Pago_Pago"],
  AD: ["Europe/Andorra"],
  AO: ["Africa/Luanda"],
  AI: ["America/Anguilla"],
  AQ: [
    "Antarctica/Casey",
    "Antarctica/Davis",
    "Antarctica/DumontDUrville",
    "Antarctica/Mawson",
    "Antarctica/McMurdo",
    "Antarctica/Palmer",
    "Antarctica/Rothera",
    "Antarctica/Syowa",
    "Antarctica/Troll",
    "Antarctica/Vostok",
  ],
  AG: ["America/Antigua"],
  AR: ["America/Jujuy"],
  AM: ["Asia/Yerevan"],
  AW: ["America/Aruba"],
  AU: [
    "Australia/Adelaide",
    "Australia/Brisbane",
    "Australia/Darwin",
    "Australia/Eucla",
    "Australia/Lord_Howe",
    "Australia/Melbourne",
    "Australia/Perth",
  ],
  AT: ["Europe/Vienna"],
  AZ: ["Asia/Baku"],
  BS: ["America/Nassau"],
  BH: ["Asia/Bahrain"],
  BD: ["Asia/Dhaka"],
  BB: ["America/Barbados"],
  BY: ["Europe/Minsk"],
  BE: ["Europe/Brussels"],
  BZ: ["America/Belize"],
  BJ: ["Africa/Porto-Novo"],
  DY: ["Africa/Porto-Novo"],
  BM: ["Atlantic/Bermuda"],
  BT: ["Asia/Thimphu"],
  BO: ["America/La_Paz"],
  BA: ["Europe/Sarajevo"],
  BW: ["Africa/Gaborone"],
  BR: ["America/Cuiaba", "America/Eirunepe", "America/Noronha", "America/Sao_Paulo"],
  IO: ["Indian/Chagos"],
  VG: ["America/Tortola"],
  BN: ["Asia/Brunei"],
  BG: ["Europe/Sofia"],
  BF: ["Africa/Ouagadougou"],
  HV: ["Africa/Ouagadougou"],
  BI: ["Africa/Bujumbura"],
  KH: ["Asia/Phnom_Penh"],
  CM: ["Africa/Douala"],
  CA: [
    "America/Blanc-Sablon",
    "America/Coral_Harbour",
    "America/Creston",
    "America/Dawson",
    "America/Edmonton",
    "America/Halifax",
    "America/Regina",
    "America/St_Johns",
    "America/Toronto",
    "America/Vancouver",
    "America/Winnipeg",
  ],
  CV: ["Atlantic/Cape_Verde"],
  BQ: ["America/Kralendijk"],
  KY: ["America/Cayman"],
  CF: ["Africa/Bangui"],
  TD: ["Africa/Ndjamena"],
  CL: ["America/Coyhaique", "America/Punta_Arenas", "America/Santiago", "Pacific/Easter"],
  CN: ["Asia/Shanghai", "Asia/Urumqi"],
  CX: ["Indian/Christmas"],
  CC: ["Indian/Cocos"],
  CO: ["America/Bogota"],
  KM: ["Indian/Comoro"],
  CG: ["Africa/Brazzaville"],
  CD: ["Africa/Kinshasa", "Africa/Lubumbashi"],
  ZR: ["Africa/Kinshasa", "Africa/Lubumbashi"],
  CK: ["Pacific/Rarotonga"],
  CR: ["America/Costa_Rica"],
  CI: ["Africa/Abidjan"],
  HR: ["Europe/Zagreb"],
  CU: ["America/Havana"],
  AN: ["America/Curacao"],
  CW: ["America/Curacao"],
  CY: ["Asia/Nicosia"],
  CZ: ["Europe/Prague"],
  DK: ["Europe/Copenhagen"],
  DJ: ["Africa/Djibouti"],
  DM: ["America/Dominica"],
  DO: ["America/Santo_Domingo"],
  EC: ["America/Guayaquil", "Pacific/Galapagos"],
  EG: ["Africa/Cairo"],
  SV: ["America/El_Salvador"],
  GQ: ["Africa/Malabo"],
  ER: ["Africa/Asmera"],
  EE: ["Europe/Tallinn"],
  SZ: ["Africa/Mbabane"],
  ET: ["Africa/Addis_Ababa"],
  FK: ["Atlantic/Stanley"],
  FO: ["Atlantic/Faroe"],
  FJ: ["Pacific/Fiji"],
  FI: ["Europe/Helsinki"],
  FR: ["Europe/Paris"],
  FX: ["Europe/Paris"],
  GF: ["America/Cayenne"],
  PF: ["Pacific/Gambier", "Pacific/Marquesas", "Pacific/Tahiti"],
  TF: ["Indian/Kerguelen"],
  GA: ["Africa/Libreville"],
  GM: ["Africa/Banjul"],
  GE: ["Asia/Tbilisi"],
  DD: ["Europe/Berlin"],
  DE: ["Europe/Berlin"],
  GH: ["Africa/Accra"],
  GI: ["Europe/Gibraltar"],
  GR: ["Europe/Athens"],
  GL: ["America/Danmarkshavn", "America/Godthab", "America/Thule"],
  GD: ["America/Grenada"],
  GP: ["America/Guadeloupe"],
  GU: ["Pacific/Guam"],
  GT: ["America/Guatemala"],
  GG: ["Europe/Guernsey"],
  GN: ["Africa/Conakry"],
  GW: ["Africa/Bissau"],
  GY: ["America/Guyana"],
  HT: ["America/Port-au-Prince"],
  HN: ["America/Tegucigalpa"],
  HK: ["Asia/Hong_Kong"],
  HU: ["Europe/Budapest"],
  IS: ["Atlantic/Reykjavik"],
  ID: ["Asia/Jakarta", "Asia/Jayapura", "Asia/Makassar"],
  IR: ["Asia/Tehran"],
  IQ: ["Asia/Baghdad"],
  IE: ["Europe/Dublin"],
  IM: ["Europe/Isle_of_Man"],
  IL: ["Asia/Jerusalem"],
  IT: ["Europe/Rome"],
  JM: ["America/Jamaica"],
  JP: ["Asia/Tokyo"],
  JE: ["Europe/Jersey"],
  JO: ["Asia/Amman"],
  KZ: ["Asia/Oral"],
  KE: ["Africa/Nairobi"],
  KI: ["Pacific/Enderbury", "Pacific/Kiritimati", "Pacific/Tarawa"],
  KW: ["Asia/Kuwait"],
  KG: ["Asia/Bishkek"],
  LA: ["Asia/Vientiane"],
  LV: ["Europe/Riga"],
  LB: ["Asia/Beirut"],
  LS: ["Africa/Maseru"],
  LR: ["Africa/Monrovia"],
  LY: ["Africa/Tripoli"],
  LI: ["Europe/Vaduz"],
  LT: ["Europe/Vilnius"],
  LU: ["Europe/Luxembourg"],
  MO: ["Asia/Macau"],
  MG: ["Indian/Antananarivo"],
  MW: ["Africa/Blantyre"],
  MY: ["Asia/Kuching"],
  MV: ["Indian/Maldives"],
  ML: ["Africa/Bamako"],
  MT: ["Europe/Malta"],
  MH: ["Pacific/Majuro"],
  MQ: ["America/Martinique"],
  MR: ["Africa/Nouakchott"],
  MU: ["Indian/Mauritius"],
  YT: ["Indian/Mayotte"],
  MX: [
    "America/Cancun",
    "America/Ciudad_Juarez",
    "America/Mazatlan",
    "America/Merida",
    "America/Ojinaga",
    "America/Tijuana",
  ],
  FM: ["Pacific/Chuuk", "Pacific/Kosrae", "Pacific/Pohnpei"],
  MD: ["Europe/Chisinau"],
  MC: ["Europe/Monaco"],
  MN: ["Asia/Hovd", "Asia/Ulaanbaatar"],
  ME: ["Europe/Podgorica"],
  MS: ["America/Montserrat"],
  MA: ["Africa/Casablanca"],
  MZ: ["Africa/Maputo"],
  BU: ["Asia/Yangon"],
  MM: ["Asia/Yangon"],
  NA: ["Africa/Windhoek"],
  NR: ["Pacific/Nauru"],
  NP: ["Asia/Kathmandu"],
  NL: ["Europe/Amsterdam"],
  NC: ["Pacific/Noumea"],
  NZ: ["Pacific/Auckland", "Pacific/Chatham"],
  NI: ["America/Managua"],
  NE: ["Africa/Niamey"],
  NG: ["Africa/Lagos"],
  NU: ["Pacific/Niue"],
  NF: ["Pacific/Norfolk"],
  KP: ["Asia/Pyongyang"],
  MK: ["Europe/Skopje"],
  MP: ["Pacific/Saipan"],
  NO: ["Europe/Oslo"],
  OM: ["Asia/Muscat"],
  PK: ["Asia/Karachi"],
  PW: ["Pacific/Palau"],
  PS: ["Asia/Gaza"],
  PA: ["America/Panama"],
  PG: ["Pacific/Bougainville", "Pacific/Port_Moresby"],
  PY: ["America/Asuncion"],
  PE: ["America/Lima"],
  PH: ["Asia/Manila"],
  PN: ["Pacific/Pitcairn"],
  PL: ["Europe/Warsaw"],
  PT: ["Atlantic/Azores", "Europe/Lisbon"],
  PR: ["America/Puerto_Rico"],
  QA: ["Asia/Qatar"],
  RE: ["Indian/Reunion"],
  RO: ["Europe/Bucharest"],
  RU: [
    "Asia/Anadyr",
    "Asia/Chita",
    "Asia/Irkutsk",
    "Asia/Magadan",
    "Asia/Omsk",
    "Asia/Tomsk",
    "Asia/Ust-Nera",
    "Asia/Yekaterinburg",
    "Europe/Kaliningrad",
    "Europe/Kirov",
    "Europe/Samara",
  ],
  SU: [
    "Asia/Anadyr",
    "Asia/Chita",
    "Asia/Irkutsk",
    "Asia/Magadan",
    "Asia/Omsk",
    "Asia/Tomsk",
    "Asia/Ust-Nera",
    "Asia/Yekaterinburg",
    "Europe/Kaliningrad",
    "Europe/Kirov",
    "Europe/Samara",
  ],
  RW: ["Africa/Kigali"],
  WS: ["Pacific/Apia"],
  SM: ["Europe/San_Marino"],
  ST: ["Africa/Sao_Tome"],
  SA: ["Asia/Riyadh"],
  SN: ["Africa/Dakar"],
  CS: ["Europe/Belgrade"],
  RS: ["Europe/Belgrade"],
  YU: ["Europe/Belgrade"],
  SC: ["Indian/Mahe"],
  SL: ["Africa/Freetown"],
  SG: ["Asia/Singapore"],
  SX: ["America/Lower_Princes"],
  SK: ["Europe/Bratislava"],
  SI: ["Europe/Ljubljana"],
  SB: ["Pacific/Guadalcanal"],
  SO: ["Africa/Mogadishu"],
  ZA: ["Africa/Johannesburg"],
  GS: ["Atlantic/South_Georgia"],
  KR: ["Asia/Seoul"],
  SS: ["Africa/Juba"],
  ES: ["Atlantic/Canary", "Europe/Madrid"],
  LK: ["Asia/Colombo"],
  BL: ["America/St_Barthelemy"],
  SH: ["Atlantic/St_Helena"],
  KN: ["America/St_Kitts"],
  LC: ["America/St_Lucia"],
  MF: ["America/Marigot"],
  PM: ["America/Miquelon"],
  VC: ["America/St_Vincent"],
  SD: ["Africa/Khartoum"],
  SR: ["America/Paramaribo"],
  SJ: ["Arctic/Longyearbyen"],
  SE: ["Europe/Stockholm"],
  CH: ["Europe/Zurich"],
  SY: ["Asia/Damascus"],
  TW: ["Asia/Taipei"],
  TJ: ["Asia/Dushanbe"],
  TZ: ["Africa/Dar_es_Salaam"],
  TH: ["Asia/Bangkok"],
  TL: ["Asia/Dili"],
  TP: ["Asia/Dili"],
  TG: ["Africa/Lome"],
  TK: ["Pacific/Fakaofo"],
  TO: ["Pacific/Tongatapu"],
  TT: ["America/Port_of_Spain"],
  TN: ["Africa/Tunis"],
  TR: ["Europe/Istanbul"],
  TM: ["Asia/Ashgabat"],
  TC: ["America/Grand_Turk"],
  TV: ["Pacific/Funafuti"],
  UM: ["Pacific/Midway", "Pacific/Wake"],
  VI: ["America/St_Thomas"],
  UG: ["Africa/Kampala"],
  UA: ["Europe/Kyiv", "Europe/Simferopol"],
  AE: ["Asia/Dubai"],
  UK: ["Europe/London"],
  UY: ["America/Montevideo"],
  UZ: ["Asia/Tashkent"],
  NH: ["Pacific/Efate"],
  VU: ["Pacific/Efate"],
  VA: ["Europe/Vatican"],
  VE: ["America/Caracas"],
  VD: ["Asia/Ho_Chi_Minh"],
  VN: ["Asia/Ho_Chi_Minh"],
  WF: ["Pacific/Wallis"],
  EH: ["Africa/El_Aaiun"],
  YD: ["Asia/Aden"],
  YE: ["Asia/Aden"],
  ZM: ["Africa/Lusaka"],
  RH: ["Africa/Harare"],
  ZW: ["Africa/Harare"],
};

export const TIME_ZONE_META: Readonly<Record<string, TimeZoneMeta>> = {
  "Africa/Abidjan": { name: "Greenwich Mean Time", abbr: "GMT" },
  "Africa/Accra": { name: "Greenwich Mean Time", abbr: "GMT" },
  "Africa/Addis_Ababa": { name: "East Africa Time", abbr: "EAT" },
  "Africa/Algiers": { name: "Central European Standard Time", abbr: "CEST" },
  "Africa/Asmera": { name: "East Africa Time", abbr: "EAT" },
  "Africa/Bamako": { name: "Greenwich Mean Time", abbr: "GMT" },
  "Africa/Bangui": { name: "West Africa Time", abbr: "WAT" },
  "Africa/Banjul": { name: "Greenwich Mean Time", abbr: "GMT" },
  "Africa/Bissau": { name: "Greenwich Mean Time", abbr: "GMT" },
  "Africa/Blantyre": { name: "Central Africa Time", abbr: "CAT" },
  "Africa/Brazzaville": { name: "West Africa Time", abbr: "WAT" },
  "Africa/Bujumbura": { name: "Central Africa Time", abbr: "CAT" },
  "Africa/Cairo": { name: "Eastern European Time", abbr: "EET" },
  "Africa/Casablanca": { name: "Morocco Time", abbr: "MT" },
  "Africa/Conakry": { name: "Greenwich Mean Time", abbr: "GMT" },
  "Africa/Dakar": { name: "Greenwich Mean Time", abbr: "GMT" },
  "Africa/Dar_es_Salaam": { name: "East Africa Time", abbr: "EAT" },
  "Africa/Djibouti": { name: "East Africa Time", abbr: "EAT" },
  "Africa/Douala": { name: "West Africa Time", abbr: "WAT" },
  "Africa/El_Aaiun": { name: "Western Sahara Time", abbr: "WST" },
  "Africa/Freetown": { name: "Greenwich Mean Time", abbr: "GMT" },
  "Africa/Gaborone": { name: "Central Africa Time", abbr: "CAT" },
  "Africa/Harare": { name: "Central Africa Time", abbr: "CAT" },
  "Africa/Johannesburg": { name: "South Africa Standard Time", abbr: "SAST" },
  "Africa/Juba": { name: "Central Africa Time", abbr: "CAT" },
  "Africa/Kampala": { name: "East Africa Time", abbr: "EAT" },
  "Africa/Khartoum": { name: "Central Africa Time", abbr: "CAT" },
  "Africa/Kigali": { name: "Central Africa Time", abbr: "CAT" },
  "Africa/Kinshasa": { name: "West Africa Time", abbr: "WAT" },
  "Africa/Lagos": { name: "West Africa Time", abbr: "WAT" },
  "Africa/Libreville": { name: "West Africa Time", abbr: "WAT" },
  "Africa/Lome": { name: "Greenwich Mean Time", abbr: "GMT" },
  "Africa/Luanda": { name: "West Africa Time", abbr: "WAT" },
  "Africa/Lubumbashi": { name: "Central Africa Time", abbr: "CAT" },
  "Africa/Lusaka": { name: "Central Africa Time", abbr: "CAT" },
  "Africa/Malabo": { name: "West Africa Time", abbr: "WAT" },
  "Africa/Maputo": { name: "Central Africa Time", abbr: "CAT" },
  "Africa/Maseru": { name: "South Africa Standard Time", abbr: "SAST" },
  "Africa/Mbabane": { name: "South Africa Standard Time", abbr: "SAST" },
  "Africa/Mogadishu": { name: "East Africa Time", abbr: "EAT" },
  "Africa/Monrovia": { name: "Greenwich Mean Time", abbr: "GMT" },
  "Africa/Nairobi": { name: "East Africa Time", abbr: "EAT" },
  "Africa/Ndjamena": { name: "West Africa Time", abbr: "WAT" },
  "Africa/Niamey": { name: "West Africa Time", abbr: "WAT" },
  "Africa/Nouakchott": { name: "Greenwich Mean Time", abbr: "GMT" },
  "Africa/Ouagadougou": { name: "Greenwich Mean Time", abbr: "GMT" },
  "Africa/Porto-Novo": { name: "West Africa Time", abbr: "WAT" },
  "Africa/Sao_Tome": { name: "Greenwich Mean Time", abbr: "GMT" },
  "Africa/Tripoli": { name: "Eastern European Standard Time", abbr: "EEST" },
  "Africa/Tunis": { name: "Central European Standard Time", abbr: "CEST" },
  "Africa/Windhoek": { name: "Central Africa Time", abbr: "CAT" },
  "America/Adak": { name: "Hawaii-Aleutian Time", abbr: "HT" },
  "America/Anchorage": { name: "Alaska Time", abbr: "AT" },
  "America/Anguilla": { name: "Atlantic Standard Time", abbr: "AST" },
  "America/Antigua": { name: "Atlantic Standard Time", abbr: "AST" },
  "America/Aruba": { name: "Atlantic Standard Time", abbr: "AST" },
  "America/Asuncion": { name: "Paraguay Standard Time", abbr: "PST" },
  "America/Barbados": { name: "Atlantic Standard Time", abbr: "AST" },
  "America/Belize": { name: "Central Standard Time", abbr: "CST" },
  "America/Blanc-Sablon": { name: "Atlantic Standard Time", abbr: "AST" },
  "America/Bogota": { name: "Colombia Standard Time", abbr: "CST" },
  "America/Cancun": { name: "Eastern Standard Time", abbr: "EST" },
  "America/Caracas": { name: "Venezuela Time", abbr: "VT" },
  "America/Cayenne": { name: "French Guiana Time", abbr: "FGT" },
  "America/Cayman": { name: "Eastern Standard Time", abbr: "EST" },
  "America/Chicago": { name: "Central Time", abbr: "CT" },
  "America/Ciudad_Juarez": { name: "Mountain Time", abbr: "MT" },
  "America/Coral_Harbour": { name: "Eastern Standard Time", abbr: "EST" },
  "America/Costa_Rica": { name: "Central Standard Time", abbr: "CST" },
  "America/Coyhaique": { name: "Coyhaique Time", abbr: "CT" },
  "America/Creston": { name: "Mountain Standard Time", abbr: "MST" },
  "America/Cuiaba": { name: "Amazon Standard Time", abbr: "AST" },
  "America/Curacao": { name: "Atlantic Standard Time", abbr: "AST" },
  "America/Danmarkshavn": { name: "Greenwich Mean Time", abbr: "GMT" },
  "America/Dawson": { name: "Yukon Time", abbr: "YT" },
  "America/Denver": { name: "Mountain Time", abbr: "MT" },
  "America/Dominica": { name: "Atlantic Standard Time", abbr: "AST" },
  "America/Edmonton": { name: "Mountain Time", abbr: "MT" },
  "America/Eirunepe": { name: "Acre Standard Time", abbr: "AST" },
  "America/El_Salvador": { name: "Central Standard Time", abbr: "CST" },
  "America/Godthab": { name: "Greenland Time", abbr: "GT" },
  "America/Grand_Turk": { name: "Eastern Time", abbr: "ET" },
  "America/Grenada": { name: "Atlantic Standard Time", abbr: "AST" },
  "America/Guadeloupe": { name: "Atlantic Standard Time", abbr: "AST" },
  "America/Guatemala": { name: "Central Standard Time", abbr: "CST" },
  "America/Guayaquil": { name: "Ecuador Time", abbr: "ET" },
  "America/Guyana": { name: "Guyana Time", abbr: "GT" },
  "America/Halifax": { name: "Atlantic Time", abbr: "AT" },
  "America/Havana": { name: "Cuba Time", abbr: "CT" },
  "America/Jamaica": { name: "Eastern Standard Time", abbr: "EST" },
  "America/Jujuy": { name: "Argentina Standard Time", abbr: "AST" },
  "America/Kralendijk": { name: "Atlantic Standard Time", abbr: "AST" },
  "America/La_Paz": { name: "Bolivia Time", abbr: "BT" },
  "America/Lima": { name: "Peru Standard Time", abbr: "PST" },
  "America/Los_Angeles": { name: "Pacific Time", abbr: "PT" },
  "America/Lower_Princes": { name: "Atlantic Standard Time", abbr: "AST" },
  "America/Managua": { name: "Central Standard Time", abbr: "CST" },
  "America/Marigot": { name: "Atlantic Standard Time", abbr: "AST" },
  "America/Martinique": { name: "Atlantic Standard Time", abbr: "AST" },
  "America/Mazatlan": { name: "Mexican Pacific Standard Time", abbr: "MPST" },
  "America/Merida": { name: "Central Standard Time", abbr: "CST" },
  "America/Miquelon": { name: "St. Pierre & Miquelon Time", abbr: "SPMT" },
  "America/Montevideo": { name: "Uruguay Standard Time", abbr: "UST" },
  "America/Montserrat": { name: "Atlantic Standard Time", abbr: "AST" },
  "America/Nassau": { name: "Eastern Time", abbr: "ET" },
  "America/New_York": { name: "Eastern Time", abbr: "ET" },
  "America/Noronha": { name: "Fernando de Noronha Standard Time", abbr: "FNST" },
  "America/Ojinaga": { name: "Central Time", abbr: "CT" },
  "America/Panama": { name: "Eastern Standard Time", abbr: "EST" },
  "America/Paramaribo": { name: "Suriname Time", abbr: "ST" },
  "America/Phoenix": { name: "Mountain Standard Time", abbr: "MST" },
  "America/Port-au-Prince": { name: "Eastern Time", abbr: "ET" },
  "America/Port_of_Spain": { name: "Atlantic Standard Time", abbr: "AST" },
  "America/Puerto_Rico": { name: "Atlantic Standard Time", abbr: "AST" },
  "America/Punta_Arenas": { name: "Punta Arenas Time", abbr: "PAT" },
  "America/Regina": { name: "Central Standard Time", abbr: "CST" },
  "America/Santiago": { name: "Chile Time", abbr: "CT" },
  "America/Santo_Domingo": { name: "Atlantic Standard Time", abbr: "AST" },
  "America/Sao_Paulo": { name: "Brasilia Standard Time", abbr: "BST" },
  "America/St_Barthelemy": { name: "Atlantic Standard Time", abbr: "AST" },
  "America/St_Johns": { name: "Newfoundland Time", abbr: "NT" },
  "America/St_Kitts": { name: "Atlantic Standard Time", abbr: "AST" },
  "America/St_Lucia": { name: "Atlantic Standard Time", abbr: "AST" },
  "America/St_Thomas": { name: "Atlantic Standard Time", abbr: "AST" },
  "America/St_Vincent": { name: "Atlantic Standard Time", abbr: "AST" },
  "America/Tegucigalpa": { name: "Central Standard Time", abbr: "CST" },
  "America/Thule": { name: "Atlantic Time", abbr: "AT" },
  "America/Tijuana": { name: "Pacific Time", abbr: "PT" },
  "America/Toronto": { name: "Eastern Time", abbr: "ET" },
  "America/Tortola": { name: "Atlantic Standard Time", abbr: "AST" },
  "America/Vancouver": { name: "Pacific Time", abbr: "PT" },
  "America/Winnipeg": { name: "Central Time", abbr: "CT" },
  "Antarctica/Casey": { name: "Australian Western Standard Time", abbr: "AWST" },
  "Antarctica/Davis": { name: "Davis Time", abbr: "DT" },
  "Antarctica/DumontDUrville": { name: "Dumont d’Urville Time", abbr: "DT" },
  "Antarctica/Mawson": { name: "Mawson Time", abbr: "MT" },
  "Antarctica/McMurdo": { name: "New Zealand Time", abbr: "NZT" },
  "Antarctica/Palmer": { name: "Palmer Land Time", abbr: "PLT" },
  "Antarctica/Rothera": { name: "Rothera Time", abbr: "RT" },
  "Antarctica/Syowa": { name: "Syowa Time", abbr: "ST" },
  "Antarctica/Troll": { name: "Troll Station Time", abbr: "TST" },
  "Antarctica/Vostok": { name: "Vostok Time", abbr: "VT" },
  "Arctic/Longyearbyen": { name: "Central European Time", abbr: "CET" },
  "Asia/Aden": { name: "Arabian Standard Time", abbr: "AST" },
  "Asia/Amman": { name: "Jordan Time", abbr: "JT" },
  "Asia/Anadyr": { name: "Kamchatka Standard Time", abbr: "KST" },
  "Asia/Ashgabat": { name: "Turkmenistan Standard Time", abbr: "TST" },
  "Asia/Baghdad": { name: "Arabian Standard Time", abbr: "AST" },
  "Asia/Bahrain": { name: "Arabian Standard Time", abbr: "AST" },
  "Asia/Baku": { name: "Azerbaijan Standard Time", abbr: "AST" },
  "Asia/Bangkok": { name: "Indochina Time", abbr: "IT" },
  "Asia/Beirut": { name: "Eastern European Time", abbr: "EET" },
  "Asia/Bishkek": { name: "Kyrgyzstan Time", abbr: "KT" },
  "Asia/Brunei": { name: "Brunei Time", abbr: "BT" },
  "Asia/Chita": { name: "Yakutsk Standard Time", abbr: "YST" },
  "Asia/Colombo": { name: "India Standard Time", abbr: "SLST" },
  "Asia/Damascus": { name: "Syria Time", abbr: "ST" },
  "Asia/Dhaka": { name: "Bangladesh Standard Time", abbr: "BST" },
  "Asia/Dili": { name: "Timor-Leste Time", abbr: "TT" },
  "Asia/Dubai": { name: "Gulf Standard Time", abbr: "GST" },
  "Asia/Dushanbe": { name: "Tajikistan Time", abbr: "TT" },
  "Asia/Gaza": { name: "Eastern European Time", abbr: "EET" },
  "Asia/Ho_Chi_Minh": { name: "Indochina Time", abbr: "IT" },
  "Asia/Hong_Kong": { name: "Hong Kong Standard Time", abbr: "HKT" },
  "Asia/Hovd": { name: "Khovd Standard Time", abbr: "KST" },
  "Asia/Irkutsk": { name: "Irkutsk Standard Time", abbr: "IST" },
  "Asia/Jakarta": { name: "Western Indonesia Time", abbr: "WIB" },
  "Asia/Jayapura": { name: "Eastern Indonesia Time", abbr: "EIT" },
  "Asia/Jerusalem": { name: "Israel Time", abbr: "IT" },
  "Asia/Kabul": { name: "Afghanistan Time", abbr: "AT" },
  "Asia/Karachi": { name: "Pakistan Standard Time", abbr: "PKT" },
  "Asia/Kathmandu": { name: "Nepal Time", abbr: "NPT" },
  "Asia/Kolkata": { name: "India Standard Time", abbr: "IST" },
  "Asia/Kuching": { name: "Malaysia Time", abbr: "MT" },
  "Asia/Kuwait": { name: "Arabian Standard Time", abbr: "AST" },
  "Asia/Macau": { name: "China Standard Time", abbr: "CST" },
  "Asia/Magadan": { name: "Magadan Standard Time", abbr: "MST" },
  "Asia/Makassar": { name: "Central Indonesia Time", abbr: "CIT" },
  "Asia/Manila": { name: "Philippine Standard Time", abbr: "PHT" },
  "Asia/Muscat": { name: "Gulf Standard Time", abbr: "GST" },
  "Asia/Nicosia": { name: "Eastern European Time", abbr: "EET" },
  "Asia/Omsk": { name: "Omsk Standard Time", abbr: "OST" },
  "Asia/Oral": { name: "Kazakhstan Time", abbr: "KT" },
  "Asia/Phnom_Penh": { name: "Indochina Time", abbr: "IT" },
  "Asia/Pyongyang": { name: "Korean Standard Time", abbr: "KST" },
  "Asia/Qatar": { name: "Arabian Standard Time", abbr: "AST" },
  "Asia/Riyadh": { name: "Arabian Standard Time", abbr: "AST" },
  "Asia/Seoul": { name: "Korean Standard Time", abbr: "KST" },
  "Asia/Shanghai": { name: "China Standard Time", abbr: "CST" },
  "Asia/Singapore": { name: "Singapore Standard Time", abbr: "SGT" },
  "Asia/Taipei": { name: "Taiwan Standard Time", abbr: "TST" },
  "Asia/Tashkent": { name: "Uzbekistan Standard Time", abbr: "UST" },
  "Asia/Tbilisi": { name: "Georgia Standard Time", abbr: "GST" },
  "Asia/Tehran": { name: "Iran Standard Time", abbr: "IST" },
  "Asia/Thimphu": { name: "Bhutan Time", abbr: "BT" },
  "Asia/Tokyo": { name: "Japan Standard Time", abbr: "JST" },
  "Asia/Tomsk": { name: "Krasnoyarsk Standard Time", abbr: "KST" },
  "Asia/Ulaanbaatar": { name: "Ulaanbaatar Standard Time", abbr: "UST" },
  "Asia/Urumqi": { name: "Ürümqi Time", abbr: null },
  "Asia/Ust-Nera": { name: "Vladivostok Standard Time", abbr: "VST" },
  "Asia/Vientiane": { name: "Indochina Time", abbr: "IT" },
  "Asia/Yangon": { name: "Myanmar Time", abbr: "MT" },
  "Asia/Yekaterinburg": { name: "Yekaterinburg Standard Time", abbr: "YST" },
  "Asia/Yerevan": { name: "Armenia Standard Time", abbr: "AST" },
  "Atlantic/Azores": { name: "Azores Time", abbr: "AT" },
  "Atlantic/Bermuda": { name: "Atlantic Time", abbr: "AT" },
  "Atlantic/Canary": { name: "Western European Time", abbr: "WET" },
  "Atlantic/Cape_Verde": { name: "Cape Verde Standard Time", abbr: "CVST" },
  "Atlantic/Faroe": { name: "Western European Time", abbr: "WET" },
  "Atlantic/Reykjavik": { name: "Greenwich Mean Time", abbr: "GMT" },
  "Atlantic/South_Georgia": { name: "South Georgia Time", abbr: "SGT" },
  "Atlantic/St_Helena": { name: "Greenwich Mean Time", abbr: "GMT" },
  "Atlantic/Stanley": { name: "Falkland Islands Standard Time", abbr: "FIST" },
  "Australia/Adelaide": { name: "Australian Central Time", abbr: "ACT" },
  "Australia/Brisbane": { name: "Australian Eastern Standard Time", abbr: "AEST" },
  "Australia/Darwin": { name: "Australian Central Standard Time", abbr: "ACST" },
  "Australia/Eucla": { name: "Australian Central Western Standard Time", abbr: "ACWST" },
  "Australia/Lord_Howe": { name: "Lord Howe Time", abbr: "LHT" },
  "Australia/Melbourne": { name: "Australian Eastern Time", abbr: "AET" },
  "Australia/Perth": { name: "Australian Western Standard Time", abbr: "AWST" },
  "Europe/Amsterdam": { name: "Central European Time", abbr: "CET" },
  "Europe/Andorra": { name: "Central European Time", abbr: "CET" },
  "Europe/Athens": { name: "Eastern European Time", abbr: "EET" },
  "Europe/Belgrade": { name: "Central European Time", abbr: "CET" },
  "Europe/Berlin": { name: "Central European Time", abbr: "CET" },
  "Europe/Bratislava": { name: "Central European Time", abbr: "CET" },
  "Europe/Brussels": { name: "Central European Time", abbr: "CET" },
  "Europe/Bucharest": { name: "Eastern European Time", abbr: "EET" },
  "Europe/Budapest": { name: "Central European Time", abbr: "CET" },
  "Europe/Chisinau": { name: "Eastern European Time", abbr: "EET" },
  "Europe/Copenhagen": { name: "Central European Time", abbr: "CET" },
  "Europe/Dublin": { name: "Ireland Time", abbr: "IT" },
  "Europe/Gibraltar": { name: "Central European Time", abbr: "CET" },
  "Europe/Guernsey": { name: "Guernsey Time", abbr: "GT" },
  "Europe/Helsinki": { name: "Eastern European Time", abbr: "EET" },
  "Europe/Isle_of_Man": { name: "Isle of Man Time", abbr: "IMT" },
  "Europe/Istanbul": { name: "Türkiye Standard Time", abbr: "TST" },
  "Europe/Jersey": { name: "Jersey Time", abbr: "JT" },
  "Europe/Kaliningrad": { name: "Eastern European Standard Time", abbr: "EEST" },
  "Europe/Kirov": { name: "Moscow Standard Time", abbr: "MST" },
  "Europe/Kyiv": { name: "Eastern European Time", abbr: "EET" },
  "Europe/Lisbon": { name: "Western European Time", abbr: "WET" },
  "Europe/Ljubljana": { name: "Central European Time", abbr: "CET" },
  "Europe/London": { name: "United Kingdom Time", abbr: "GMT" },
  "Europe/Luxembourg": { name: "Central European Time", abbr: "CET" },
  "Europe/Madrid": { name: "Central European Time", abbr: "CET" },
  "Europe/Malta": { name: "Central European Time", abbr: "CET" },
  "Europe/Mariehamn": { name: "Eastern European Time", abbr: "EET" },
  "Europe/Minsk": { name: "Moscow Standard Time", abbr: "MST" },
  "Europe/Monaco": { name: "Central European Time", abbr: "CET" },
  "Europe/Oslo": { name: "Central European Time", abbr: "CET" },
  "Europe/Paris": { name: "Central European Time", abbr: "CET" },
  "Europe/Podgorica": { name: "Central European Time", abbr: "CET" },
  "Europe/Prague": { name: "Central European Time", abbr: "CET" },
  "Europe/Riga": { name: "Eastern European Time", abbr: "EET" },
  "Europe/Rome": { name: "Central European Time", abbr: "CET" },
  "Europe/Samara": { name: "Samara Standard Time", abbr: "SST" },
  "Europe/San_Marino": { name: "Central European Time", abbr: "CET" },
  "Europe/Sarajevo": { name: "Central European Time", abbr: "CET" },
  "Europe/Simferopol": { name: "Moscow Standard Time", abbr: "MST" },
  "Europe/Skopje": { name: "Central European Time", abbr: "CET" },
  "Europe/Sofia": { name: "Eastern European Time", abbr: "EET" },
  "Europe/Stockholm": { name: "Central European Time", abbr: "CET" },
  "Europe/Tallinn": { name: "Eastern European Time", abbr: "EET" },
  "Europe/Tirane": { name: "Central European Time", abbr: "CET" },
  "Europe/Vaduz": { name: "Central European Time", abbr: "CET" },
  "Europe/Vatican": { name: "Central European Time", abbr: "CET" },
  "Europe/Vienna": { name: "Central European Time", abbr: "CET" },
  "Europe/Vilnius": { name: "Eastern European Time", abbr: "EET" },
  "Europe/Warsaw": { name: "Central European Time", abbr: "CET" },
  "Europe/Zagreb": { name: "Central European Time", abbr: "CET" },
  "Europe/Zurich": { name: "Central European Time", abbr: "CET" },
  "Indian/Antananarivo": { name: "East Africa Time", abbr: "EAT" },
  "Indian/Chagos": { name: "Indian Ocean Time", abbr: "IOT" },
  "Indian/Christmas": { name: "Christmas Island Time", abbr: "CIT" },
  "Indian/Cocos": { name: "Cocos Islands Time", abbr: "CIT" },
  "Indian/Comoro": { name: "East Africa Time", abbr: "EAT" },
  "Indian/Kerguelen": { name: "French Southern & Antarctic Time", abbr: "FSAT" },
  "Indian/Mahe": { name: "Seychelles Time", abbr: "ST" },
  "Indian/Maldives": { name: "Maldives Time", abbr: "MT" },
  "Indian/Mauritius": { name: "Mauritius Standard Time", abbr: "MST" },
  "Indian/Mayotte": { name: "East Africa Time", abbr: "EAT" },
  "Indian/Reunion": { name: "Réunion Time", abbr: "RT" },
  "Pacific/Apia": { name: "Samoa Standard Time", abbr: "SST" },
  "Pacific/Auckland": { name: "New Zealand Time", abbr: "NZST" },
  "Pacific/Bougainville": { name: "Bougainville Time", abbr: "BT" },
  "Pacific/Chatham": { name: "Chatham Time", abbr: "CT" },
  "Pacific/Chuuk": { name: "Chuuk Time", abbr: "CT" },
  "Pacific/Easter": { name: "Easter Island Time", abbr: "EIT" },
  "Pacific/Efate": { name: "Vanuatu Standard Time", abbr: "VST" },
  "Pacific/Enderbury": { name: "Phoenix Islands Time", abbr: "PIT" },
  "Pacific/Fakaofo": { name: "Tokelau Time", abbr: "TT" },
  "Pacific/Fiji": { name: "Fiji Standard Time", abbr: "FST" },
  "Pacific/Funafuti": { name: "Tuvalu Time", abbr: "TT" },
  "Pacific/Galapagos": { name: "Galapagos Time", abbr: "GT" },
  "Pacific/Gambier": { name: "Gambier Time", abbr: "GT" },
  "Pacific/Guadalcanal": { name: "Solomon Islands Time", abbr: "SIT" },
  "Pacific/Guam": { name: "Chamorro Standard Time", abbr: "CST" },
  "Pacific/Honolulu": { name: "Hawaii-Aleutian Standard Time", abbr: "HST" },
  "Pacific/Kiritimati": { name: "Line Islands Time", abbr: "LIT" },
  "Pacific/Kosrae": { name: "Kosrae Time", abbr: "KT" },
  "Pacific/Majuro": { name: "Marshall Islands Time", abbr: "MIT" },
  "Pacific/Marquesas": { name: "Marquesas Time", abbr: "MT" },
  "Pacific/Midway": { name: "American Samoa Standard Time", abbr: "ASST" },
  "Pacific/Nauru": { name: "Nauru Time", abbr: "NT" },
  "Pacific/Niue": { name: "Niue Time", abbr: "NT" },
  "Pacific/Norfolk": { name: "Norfolk Island Time", abbr: "NIT" },
  "Pacific/Noumea": { name: "New Caledonia Standard Time", abbr: "NCST" },
  "Pacific/Pago_Pago": { name: "American Samoa Standard Time", abbr: "ASST" },
  "Pacific/Palau": { name: "Palau Time", abbr: "PT" },
  "Pacific/Pitcairn": { name: "Pitcairn Time", abbr: "PT" },
  "Pacific/Pohnpei": { name: "Pohnpei Time", abbr: "PT" },
  "Pacific/Port_Moresby": { name: "Papua New Guinea Time", abbr: "PNGT" },
  "Pacific/Rarotonga": { name: "Cook Islands Standard Time", abbr: "CIST" },
  "Pacific/Saipan": { name: "Chamorro Standard Time", abbr: "CST" },
  "Pacific/Tahiti": { name: "Tahiti Time", abbr: "TT" },
  "Pacific/Tarawa": { name: "Gilbert Islands Time", abbr: "GIT" },
  "Pacific/Tongatapu": { name: "Tonga Standard Time", abbr: "TST" },
  "Pacific/Wake": { name: "Wake Island Time", abbr: "WIT" },
  "Pacific/Wallis": { name: "Wallis & Futuna Time", abbr: "WFT" },
};

const COUNTRY_CODES = new Set(COUNTRIES.map((country) => country.code));

export function isCountryCode(value: string): boolean {
  return COUNTRY_CODES.has(value);
}

export function countryName(code: string): string {
  return COUNTRIES.find((country) => country.code === code)?.name ?? code;
}

export function timeZonesForCountry(code: string): readonly string[] {
  return TIME_ZONES_BY_COUNTRY[code] ?? [];
}

/**
 * The pair check the server needs: a zone is only valid for the country it
 * belongs to, so "India + America/Los_Angeles" cannot be stored.
 */
export function isTimeZoneInCountry(timeZone: string, countryCode: string): boolean {
  return timeZonesForCountry(countryCode).includes(timeZone);
}

/**
 * A time zone the platform knows about.
 *
 * Published here, beside the data it checks against, rather than defined
 * privately by each caller — the expert application and the scheduled-callback
 * form both need it, and two copies of a validation rule is one that drifts.
 *
 * It admits IANA ids only. An offset like `+05:30` fails, deliberately: an offset
 * has forgotten which country's rules produced it and so cannot survive a
 * daylight-saving change.
 */
export const timeZoneIdSchema = z
  .string()
  .trim()
  .refine((value) => value in TIME_ZONE_META, "Choose a time zone from the list");
