import js from "@eslint/js";
import tseslint from "typescript-eslint";
import prettier from "eslint-config-prettier";
import globals from "globals";

/** Shared baseline for every package in the monorepo. */
export default tseslint.config(
  {
    ignores: [
      "**/dist/**",
      "**/.next/**",
      "**/node_modules/**",
      "**/.turbo/**",
      "**/coverage/**",
      "**/generated/**",
      "**/*.config.{js,mjs,cjs}",
      // Generated by `next build`; its triple-slash references are not ours to fix.
      "**/next-env.d.ts",
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  {
    rules: {
      // §37.11 — avoid `any` unless absolutely necessary.
      "@typescript-eslint/no-explicit-any": "error",
      "@typescript-eslint/no-unused-vars": [
        "error",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_", caughtErrorsIgnorePattern: "^_" },
      ],
      "@typescript-eslint/consistent-type-imports": [
        "error",
        { prefer: "type-imports", fixStyle: "inline-type-imports" },
      ],
      "@typescript-eslint/no-non-null-assertion": "warn",

      // Money is integer minor units everywhere (§3). Floats are a correctness bug.
      //
      // Targets the specific mistake — rounding a value divided by 100, i.e.
      // converting minor units to major and losing the remainder — rather than
      // every `Math.round`. Byte formatting (/1024) and durations (/1000) are
      // legitimate and must not be flagged, or the rule gets disabled wholesale
      // and stops protecting anything.
      "no-restricted-syntax": [
        "error",
        {
          selector:
            "CallExpression[callee.object.name='Math'][callee.property.name=/^(round|floor|ceil)$/] > BinaryExpression[operator='/'][right.value=100]",
          message:
            "Rounding a minor-unit amount to major units loses the remainder. Use the Money helpers in @sfx/domain/shared/money, or Intl.NumberFormat for display.",
        },
      ],

      eqeqeq: ["error", "always", { null: "ignore" }],
      "no-console": ["warn", { allow: ["warn", "error"] }],
      "prefer-const": "error",
    },
  },
  {
    // Operational scripts: plain Node ESM, and console output is the point.
    files: ["scripts/**/*.mjs", "scripts/**/*.js", "*.mjs"],
    languageOptions: {
      globals: globals.node,
      sourceType: "module",
    },
    rules: {
      "no-console": "off",
    },
  },
  prettier,
);
